### PR TITLE
Configure correct main branch

### PR DESCRIPTION
**Pull request by timbussmann**
This will probably cause issues with repo-sync, either forcing us to ignore repo-sync for this file or changing renaming the main branch to master to align with the automatically synced settings.

### CODE REVIEW

**Comment by mikeminutillo** [comment]
I'm not certain that this is necessary. GitVersion uses named configs with regexes to determine whether a branch fits the config or not and I think it recognizes main and master as being interchangeable. There's some detail about this in https://github.com/GitTools/GitVersion/issues/2570

To test this, I ran `dotnet-gitversion /showconfig` on this PR and on main and diff'd the results. There is no difference. Both of them treat "master" config as if it were called main.

Here is the output from the main branch.

```
assembly-versioning-scheme: Major
assembly-file-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
tag-pre-release-weight: 60000
commit-message-incrementing: Enabled
branches:
  main:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^master$|^main$
    source-branches:
    - develop
    - release
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  release:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^releases?[/-]
    source-branches:
    - develop
    - main
    - support
    - release
    tracks-release-branches: false
    is-release-branch: true
    is-mainline: false
    pre-release-weight: 30000
  develop:
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    regex: ^dev(elop)?(ment)?$
    source-branches: []
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 0
  feature:
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^features?[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  pull-request:
    mode: ContinuousDelivery
    tag: PullRequest
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    tag-number-pattern: '[/-](?<number>\d+)'
    track-merge-target: false
    regex: ^(pull|pull\-requests|pr)[/-]
    source-branches:
    - develop
    - main
    - release
    - feature
    - support
    - hotfix
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  hotfix:
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    regex: ^hotfix(es)?[/-]
    source-branches:
    - develop
    - main
    - support
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
    pre-release-weight: 30000
  support:
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    regex: ^support[/-]
    source-branches:
    - main
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
ignore:
  sha: []
commit-date-format: yyyy-MM-dd
merge-message-formats: {}
update-build-number: true
```

**Comment by mikeminutillo** [comment]
This feature was added in 5.6.5, there was a bug fixed in 5.6.6, and we are using 5.6.11

**Comment by timbussmann** [comment]
happy to close this as a non-issue then 👍 should this be documented somehow (e.g. as a comment on the yaml template)?

**Comment by mikeminutillo** [comment]
> happy to close this as a non-issue then 👍 should this be documented somehow (e.g. as a comment on the yaml template)?

That would make sense but will need to be done in RepoStandards which will trigger a PR to everywhere, right?

**Comment by timbussmann** [comment]
> That would make sense but will need to be done in RepoStandards which will trigger a PR to everywhere, right?

afaik the GHA templates are not in the repo standards as they are defined as org-wide templates.

**Pull request closed without merging**
